Repository WeGrus/WeGrus-BE-Spring, pull requests merged in 2022-01, with the labels that each got.

#5 라이브러리 업데이트, gitignore에 설정파일 추가
  .gitignore
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: bug, enhancement

#10 Redis, Security, Jwt 관련 설정 및 예외 처리, AWS 배포 에러 해결
  build.gradle
  src/main/java/wegrus/clubwebsite/advice/GlobalExceptionHandler.java
  src/main/java/wegrus/clubwebsite/config/JwtAccessDeniedHandler.java
  src/main/java/wegrus/clubwebsite/config/JwtAuthenticationEntryPoint.java
  src/main/java/wegrus/clubwebsite/config/JwtRequestFilter.java
  src/main/java/wegrus/clubwebsite/config/RedisConfig.java
  src/main/java/wegrus/clubwebsite/config/WebSecurityConfig.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorResponse.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultResponse.java
  src/main/java/wegrus/clubwebsite/exception/BusinessException.java
  src/main/java/wegrus/clubwebsite/util/JwtTokenUtil.java
  src/main/java/wegrus/clubwebsite/util/JwtUserDetailsUtil.java
  src/main/java/wegrus/clubwebsite/util/RedisUtil.java
  src/test/java/wegrus/clubwebsite/ClubWebsiteApplicationTests.java
Labels: bug, enhancement

#11 회원가입, 이메일 인증, 로그인, 로그아웃, 토큰 재발급 API 추가
  .gitignore
  build.gradle
  src/main/java/wegrus/clubwebsite/ClubWebsiteApplication.java
  src/main/java/wegrus/clubwebsite/config/EmbeddedRedisConfig.java
  src/main/java/wegrus/clubwebsite/config/QuerydslConfig.java
  src/main/java/wegrus/clubwebsite/config/WebSecurityConfig.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/Status.java
  src/main/java/wegrus/clubwebsite/dto/VerificationResponse.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/EmailCheckResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/JwtDto.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberAndJwtDto.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSigninFailResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSigninSuccessResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSignoutResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSignupRequest.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSignupResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/ReIssueResponse.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultResponse.java
  src/main/java/wegrus/clubwebsite/entity/Member.java
  src/main/java/wegrus/clubwebsite/entity/MemberAcademicStatus.java
  src/main/java/wegrus/clubwebsite/entity/MemberGrade.java
  src/main/java/wegrus/clubwebsite/entity/MemberRole.java
  src/main/java/wegrus/clubwebsite/exception/AuthorizationHeaderInvalidException.java
  src/main/java/wegrus/clubwebsite/exception/JwtInvalidException.java
  src/main/java/wegrus/clubwebsite/exception/MemberAlreadyExistException.java
  src/main/java/wegrus/clubwebsite/exception/MemberNotFoundException.java
  src/main/java/wegrus/clubwebsite/exception/RefreshTokenExpiredException.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepository.java
  src/main/java/wegrus/clubwebsite/service/MailService.java
  src/main/java/wegrus/clubwebsite/service/MailServiceGmail.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/main/java/wegrus/clubwebsite/util/JwtTokenUtil.java
  src/test/java/wegrus/clubwebsite/ClubWebsiteApplicationTests.java
  src/test/java/wegrus/clubwebsite/member/MemberControllerTest.java
  src/test/java/wegrus/clubwebsite/member/MemberIntegrationTest.java
  src/test/java/wegrus/clubwebsite/member/MemberRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberServiceTest.java
Labels: enhancement

#14 게시판 관련 엔티티들 추가, 테스트코드 작성
  src/main/java/wegrus/clubwebsite/entity/Board.java
  src/main/java/wegrus/clubwebsite/entity/BoardCategory.java
  src/main/java/wegrus/clubwebsite/entity/BoardState.java
  src/main/java/wegrus/clubwebsite/entity/BoardType.java
  src/main/java/wegrus/clubwebsite/entity/CommentLike.java
  src/main/java/wegrus/clubwebsite/entity/Member.java
  src/main/java/wegrus/clubwebsite/entity/PostLike.java
  src/main/java/wegrus/clubwebsite/entity/Reply.java
  src/main/java/wegrus/clubwebsite/entity/ReplyState.java
  src/main/java/wegrus/clubwebsite/entity/View.java
  src/main/java/wegrus/clubwebsite/repository/BoardRepository.java
  src/main/java/wegrus/clubwebsite/repository/CommentLikeRepository.java
  src/main/java/wegrus/clubwebsite/repository/PostLikeRepository.java
  src/main/java/wegrus/clubwebsite/repository/ReplyRepository.java
  src/main/java/wegrus/clubwebsite/repository/ViewRepository.java
  src/test/java/wegrus/clubwebsite/Board/BoardRepositoryTest.java
Labels: enhancement

#17 회원 테스트 오류 수정, 관련 엔티티별로 디렉토리로 묶기
  build.gradle
  src/main/java/wegrus/clubwebsite/config/EmbeddedRedisConfig.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberAndJwtDto.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSigninSuccessResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSignupRequest.java
  src/main/java/wegrus/clubwebsite/entity/board/Board.java
  src/main/java/wegrus/clubwebsite/entity/board/BoardCategory.java
  src/main/java/wegrus/clubwebsite/entity/board/BoardState.java
  src/main/java/wegrus/clubwebsite/entity/board/BoardType.java
  src/main/java/wegrus/clubwebsite/entity/board/CommentLike.java
  src/main/java/wegrus/clubwebsite/entity/board/PostLike.java
  src/main/java/wegrus/clubwebsite/entity/board/Reply.java
  src/main/java/wegrus/clubwebsite/entity/board/ReplyState.java
  src/main/java/wegrus/clubwebsite/entity/board/View.java
  src/main/java/wegrus/clubwebsite/entity/member/Member.java
  src/main/java/wegrus/clubwebsite/entity/member/MemberAcademicStatus.java
  src/main/java/wegrus/clubwebsite/entity/member/MemberGrade.java
  src/main/java/wegrus/clubwebsite/entity/member/MemberRole.java
  src/main/java/wegrus/clubwebsite/repository/BoardRepository.java
  src/main/java/wegrus/clubwebsite/repository/CommentLikeRepository.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepository.java
  src/main/java/wegrus/clubwebsite/repository/PostLikeRepository.java
  src/main/java/wegrus/clubwebsite/repository/ReplyRepository.java
  src/main/java/wegrus/clubwebsite/repository/ViewRepository.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/main/java/wegrus/clubwebsite/util/JwtUserDetailsUtil.java
  src/test/java/wegrus/clubwebsite/Board/BoardRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberControllerTest.java
  src/test/java/wegrus/clubwebsite/member/MemberIntegrationTest.java
  src/test/java/wegrus/clubwebsite/member/MemberRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberServiceTest.java
Labels: bug, refactor

#23 회원 정보 수정 API 추가
  build.gradle
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberInfoUpdateRequest.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberInfoUpdateResponse.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/member/Member.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/test/java/wegrus/clubwebsite/member/MemberControllerTest.java
  src/test/java/wegrus/clubwebsite/member/MemberIntegrationTest.java
  src/test/java/wegrus/clubwebsite/member/MemberServiceTest.java
Labels: enhancement

#26 회원 이미지 변경 API 추가
  .gitignore
  build.gradle
  src/main/java/wegrus/clubwebsite/config/AmazonS3Config.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberDto.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberImageUpdateResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSimpleDto.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/member/Member.java
  src/main/java/wegrus/clubwebsite/exception/MemberImageAlreadyBasicException.java
  src/main/java/wegrus/clubwebsite/exception/MultipartfileConvertException.java
  src/main/java/wegrus/clubwebsite/exception/NotSupportedImageTypeException.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/main/java/wegrus/clubwebsite/util/AmazonS3Util.java
  src/main/java/wegrus/clubwebsite/util/ImageUtil.java
  src/main/java/wegrus/clubwebsite/vo/Image.java
  src/main/java/wegrus/clubwebsite/vo/ImageType.java
  src/main/resources/application.yml
  src/test/java/wegrus/clubwebsite/member/MemberControllerTest.java
  src/test/java/wegrus/clubwebsite/member/MemberServiceTest.java
  src/test/resources/static/image.jpg
Labels: enhancement

#29 게시물 추천/해제, 댓글 추천/해제 api 추가
  src/main/java/wegrus/clubwebsite/controller/BoardController.java
  src/main/java/wegrus/clubwebsite/dto/board/CommentLikeCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/board/PostLikeCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/exception/CommentLikeAlreadyExistException.java
  src/main/java/wegrus/clubwebsite/exception/CommentLikeNotFoundException.java
  src/main/java/wegrus/clubwebsite/exception/PostLikeAlreadyExistException.java
  src/main/java/wegrus/clubwebsite/exception/PostLikeNotFoundException.java
  src/main/java/wegrus/clubwebsite/repository/CommentLikeRepository.java
  src/main/java/wegrus/clubwebsite/repository/PostLikeRepository.java
  src/main/java/wegrus/clubwebsite/service/BoardService.java
  src/main/java/wegrus/clubwebsite/service/ReplyService.java
Labels: enhancement

#33 회원 권한 요청 API 추가
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/member/RequestAuthorityResponse.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/Request.java
  src/main/java/wegrus/clubwebsite/exception/MemberAlreadyHasRoleException.java
  src/main/java/wegrus/clubwebsite/repository/MemberRoleRepository.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/test/java/wegrus/clubwebsite/member/MemberControllerTest.java
  src/test/java/wegrus/clubwebsite/member/MemberIntegrationTest.java
  src/test/java/wegrus/clubwebsite/member/MemberServiceTest.java
Labels: enhancement

#37 회원 탈퇴 API, 회원 재가입 로직 추가
  src/main/java/wegrus/clubwebsite/config/SetupConfig.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/StatusResponse.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/member/Member.java
  src/main/java/wegrus/clubwebsite/entity/member/MemberAcademicStatus.java
  src/main/java/wegrus/clubwebsite/entity/member/MemberGrade.java
  src/main/java/wegrus/clubwebsite/entity/member/MemberRoles.java
  src/main/java/wegrus/clubwebsite/exception/MemberAlreadyBanException.java
  src/main/java/wegrus/clubwebsite/exception/MemberAlreadyResignException.java
  src/main/java/wegrus/clubwebsite/exception/MemberResignException.java
  src/main/java/wegrus/clubwebsite/repository/MemberRoleRepository.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/main/java/wegrus/clubwebsite/util/JwtUserDetailsUtil.java
  src/main/java/wegrus/clubwebsite/util/KakaoUtil.java
  src/test/java/wegrus/clubwebsite/Board/BoardRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberControllerTest.java
  src/test/java/wegrus/clubwebsite/member/MemberIntegrationTest.java
  src/test/java/wegrus/clubwebsite/member/MemberRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberRoleRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberServiceTest.java
Labels: enhancement

#38 게시판 DB 구조 변경
  src/main/java/wegrus/clubwebsite/config/SetupConfig.java
  src/main/java/wegrus/clubwebsite/controller/PostController.java
  src/main/java/wegrus/clubwebsite/dto/board/BoardCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/board/BoardUpdateResponse.java
  src/main/java/wegrus/clubwebsite/dto/board/CommentLikeCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/post/PostCreateRequest.java
  src/main/java/wegrus/clubwebsite/dto/post/PostCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/post/PostLikeCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/post/PostUpdateRequest.java
  src/main/java/wegrus/clubwebsite/dto/post/PostUpdateResponse.java
  src/main/java/wegrus/clubwebsite/dto/post/ReplyCreateRequest.java
  src/main/java/wegrus/clubwebsite/dto/post/ReplyCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/post/ReplyLikeCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/board/BoardCategory.java
  src/main/java/wegrus/clubwebsite/entity/board/BoardState.java
  src/main/java/wegrus/clubwebsite/entity/board/BoardType.java
  src/main/java/wegrus/clubwebsite/entity/member/Member.java
  src/main/java/wegrus/clubwebsite/entity/post/Board.java
  src/main/java/wegrus/clubwebsite/entity/post/BoardCategories.java
  src/main/java/wegrus/clubwebsite/entity/post/BoardCategory.java
  src/main/java/wegrus/clubwebsite/entity/post/Post.java
  src/main/java/wegrus/clubwebsite/entity/post/PostLike.java
  src/main/java/wegrus/clubwebsite/entity/post/PostState.java
  src/main/java/wegrus/clubwebsite/entity/post/PostType.java
  src/main/java/wegrus/clubwebsite/entity/post/Reply.java
  src/main/java/wegrus/clubwebsite/entity/post/ReplyLike.java
  src/main/java/wegrus/clubwebsite/entity/post/ReplyState.java
  src/main/java/wegrus/clubwebsite/entity/post/View.java
  src/main/java/wegrus/clubwebsite/exception/BoardMemberNotMatchException.java
  src/main/java/wegrus/clubwebsite/exception/CommentLikeAlreadyExistException.java
  src/main/java/wegrus/clubwebsite/exception/CommentLikeNotFoundException.java
  src/main/java/wegrus/clubwebsite/exception/PostMemberNotMatchException.java
  src/main/java/wegrus/clubwebsite/exception/PostNotFoundException.java
  src/main/java/wegrus/clubwebsite/exception/ReplyLikeAlreadyExistException.java
  src/main/java/wegrus/clubwebsite/exception/ReplyLikeNotFoundException.java
  src/main/java/wegrus/clubwebsite/repository/BoardCategoryRepository.java
  src/main/java/wegrus/clubwebsite/repository/BoardRepository.java
  src/main/java/wegrus/clubwebsite/repository/CommentLikeRepository.java
  src/main/java/wegrus/clubwebsite/repository/PostLikeRepository.java
  src/main/java/wegrus/clubwebsite/repository/PostRepository.java
  src/main/java/wegrus/clubwebsite/repository/ReplyLikeRepository.java
  src/main/java/wegrus/clubwebsite/repository/ReplyRepository.java
  src/main/java/wegrus/clubwebsite/repository/ViewRepository.java
  src/main/java/wegrus/clubwebsite/service/PostService.java
  src/main/java/wegrus/clubwebsite/service/ReplyService.java
  src/test/java/wegrus/clubwebsite/Board/BoardRepositoryTest.java
  src/test/java/wegrus/clubwebsite/Board/PostRepositoryTest.java
Labels: refactor
