Repository WeGrus/WeGrus-BE-Spring, pull requests merged in 2022-02, with the labels that each got.

#44 회원 탈퇴 API -> 이메일 인증 로직 추가
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/service/CertificationCodeInvalidException.java
  src/main/java/wegrus/clubwebsite/service/MailService.java
  src/main/java/wegrus/clubwebsite/service/MailServiceGmail.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/test/java/wegrus/clubwebsite/member/MemberControllerTest.java
  src/test/java/wegrus/clubwebsite/member/MemberIntegrationTest.java
  src/test/java/wegrus/clubwebsite/member/MemberServiceTest.java
Labels: enhancement

#41 게시물 조회 api, 게시판 추가/삭제/조회 api 추가
  src/main/java/wegrus/clubwebsite/config/SetupConfig.java
  src/main/java/wegrus/clubwebsite/config/WebSecurityConfig.java
  src/main/java/wegrus/clubwebsite/controller/PostController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/post/BoardCreateRequest.java
  src/main/java/wegrus/clubwebsite/dto/post/BoardCreateResponse.java
  src/main/java/wegrus/clubwebsite/dto/post/BoardDto.java
  src/main/java/wegrus/clubwebsite/dto/post/BoardResponse.java
  src/main/java/wegrus/clubwebsite/dto/post/PostCreateRequest.java
  src/main/java/wegrus/clubwebsite/dto/post/PostDto.java
  src/main/java/wegrus/clubwebsite/dto/post/PostResponse.java
  src/main/java/wegrus/clubwebsite/dto/post/PostUnknownDto.java
  src/main/java/wegrus/clubwebsite/dto/post/ReplyDto.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/post/Boards.java
  src/main/java/wegrus/clubwebsite/exception/BoardCategoryNotFoundException.java
  src/main/java/wegrus/clubwebsite/repository/ViewRepository.java
  src/main/java/wegrus/clubwebsite/service/PostService.java
Labels: enhancement

#46 제목, 제목+내용, 작성자 검색 api 추가
  src/main/java/wegrus/clubwebsite/controller/PostController.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/repository/PostRepository.java
  src/main/java/wegrus/clubwebsite/service/PostService.java
Labels: enhancement

#50 Feature/mypage
  src/main/java/wegrus/clubwebsite/config/SetupConfig.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSignupRequest.java
  src/main/java/wegrus/clubwebsite/dto/post/BookmarkDto.java
  src/main/java/wegrus/clubwebsite/dto/post/PostDto.java
  src/main/java/wegrus/clubwebsite/dto/post/PostReplyDto.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/member/Gender.java
  src/main/java/wegrus/clubwebsite/entity/member/Member.java
  src/main/java/wegrus/clubwebsite/entity/post/Bookmark.java
  src/main/java/wegrus/clubwebsite/repository/PostRepository.java
  src/main/java/wegrus/clubwebsite/repository/PostRepositoryQuerydsl.java
  src/main/java/wegrus/clubwebsite/repository/PostRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/test/java/wegrus/clubwebsite/Board/PostRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberControllerTest.java
  src/test/java/wegrus/clubwebsite/member/MemberIntegrationTest.java
  src/test/java/wegrus/clubwebsite/member/MemberRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberRoleRepositoryTest.java
  src/test/java/wegrus/clubwebsite/member/MemberServiceTest.java
Labels: enhancement, 💻 Need To Write Test Code

#55 그룹 가입 신청 API 추가 등
  src/main/java/wegrus/clubwebsite/config/JwtAccessDeniedHandler.java
  src/main/java/wegrus/clubwebsite/config/JwtRequestFilter.java
  src/main/java/wegrus/clubwebsite/config/SetupConfig.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/group/Group.java
  src/main/java/wegrus/clubwebsite/entity/group/GroupMember.java
  src/main/java/wegrus/clubwebsite/entity/group/GroupRoles.java
  src/main/java/wegrus/clubwebsite/entity/group/Groups.java
  src/main/java/wegrus/clubwebsite/entity/member/Member.java
  src/main/java/wegrus/clubwebsite/exception/AuthorizationCodeInvalidException.java
  src/main/java/wegrus/clubwebsite/exception/GroupMemberAlreadyExistException.java
  src/main/java/wegrus/clubwebsite/exception/GroupNotFoundException.java
  src/main/java/wegrus/clubwebsite/exception/JwtInvalidException.java
  src/main/java/wegrus/clubwebsite/repository/GroupMemberRepository.java
  src/main/java/wegrus/clubwebsite/repository/GroupRepository.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/main/java/wegrus/clubwebsite/util/JwtTokenUtil.java
  src/main/java/wegrus/clubwebsite/util/KakaoUtil.java
Labels: bug, enhancement

#59 권한 부여/요청 목록 조회 API 추가 등
  src/main/java/wegrus/clubwebsite/controller/ClubController.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/member/RequestAuthorityFailResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/RequestAuthorityResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/RequestAuthoritySuccessResponse.java
  src/main/java/wegrus/clubwebsite/dto/member/RequestDto.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/exception/CannotRequestAuthorityException.java
  src/main/java/wegrus/clubwebsite/exception/InsufficientAuthorityException.java
  src/main/java/wegrus/clubwebsite/exception/RequestNotFoundException.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepository.java
  src/main/java/wegrus/clubwebsite/repository/RequestRepository.java
  src/main/java/wegrus/clubwebsite/repository/RequestRepositoryQuerydsl.java
  src/main/java/wegrus/clubwebsite/repository/RequestRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/service/ClubService.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
  src/main/java/wegrus/clubwebsite/util/JwtUserDetailsUtil.java
Labels: enhancement, refactor

#63 회원 검색/목록 조회 API 추가
  src/main/java/wegrus/clubwebsite/config/WebSecurityConfig.java
  src/main/java/wegrus/clubwebsite/controller/ClubController.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSearchType.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSortType.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepository.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepositoryQuerydsl.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/service/ClubService.java
Labels: enhancement

#64 회원 검색(타입별), 그룹 목록 조회 API 추가
  src/main/java/wegrus/clubwebsite/controller/ClubController.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/member/GroupDto.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberDto.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberRoleSearchType.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSimpleDto.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/entity/group/Group.java
  src/main/java/wegrus/clubwebsite/entity/member/Member.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepositoryQuerydsl.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/service/ClubService.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
Labels: enhancement

#66 회원 권한 해제, 회원 강제 탈퇴 API 추가 등
  src/main/java/wegrus/clubwebsite/controller/ClubController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberRoleDeleteType.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/exception/CannotBanMember.java
  src/main/java/wegrus/clubwebsite/repository/GroupMemberRepository.java
  src/main/java/wegrus/clubwebsite/repository/MemberRoleRepository.java
  src/main/java/wegrus/clubwebsite/service/ClubService.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
Labels: enhancement

#73 Feature/#69#70#71#72
  src/main/java/wegrus/clubwebsite/config/WebSecurityConfig.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/member/GroupDto.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberDto.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberSimpleDto.java
  src/main/java/wegrus/clubwebsite/entity/group/GroupRoles.java
  src/main/java/wegrus/clubwebsite/entity/member/Gender.java
  src/main/java/wegrus/clubwebsite/entity/member/MemberAcademicStatus.java
  src/main/java/wegrus/clubwebsite/entity/member/MemberGrade.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/service/ClubService.java
  src/main/java/wegrus/clubwebsite/service/MailService.java
  src/main/java/wegrus/clubwebsite/service/MailServiceGmail.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
Labels: bug, enhancement

#81 그룹 가입 신청 목록 조회 API 확장 등
  src/main/java/wegrus/clubwebsite/controller/GroupController.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/repository/PostRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/repository/RequestRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/service/GroupService.java
Labels: bug, enhancement

#83 회원 권한 요청 승인/거절 API 추가
  src/main/java/wegrus/clubwebsite/controller/ClubController.java
  src/main/java/wegrus/clubwebsite/controller/GroupController.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberEmpowerType.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/service/ClubService.java
Labels: enhancement

#85 그룹 게시판 공지 등록/해제 api 추가
  src/main/java/wegrus/clubwebsite/controller/PostController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/exception/CannotUpdateGroupPostException.java
  src/main/java/wegrus/clubwebsite/exception/CannotUpdateNonGroupPostException.java
  src/main/java/wegrus/clubwebsite/service/PostService.java
Labels: enhancement

#88 그룹원 검색 API 추가 등
  src/main/java/wegrus/clubwebsite/controller/ClubController.java
  src/main/java/wegrus/clubwebsite/controller/GroupController.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberEmpowerType.java
  src/main/java/wegrus/clubwebsite/dto/member/RequesterSearchType.java
  src/main/java/wegrus/clubwebsite/dto/result/ResultCode.java
  src/main/java/wegrus/clubwebsite/exception/MemberAlreadyApplyGroupException.java
  src/main/java/wegrus/clubwebsite/repository/GroupMemberRepository.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepositoryQuerydsl.java
  src/main/java/wegrus/clubwebsite/repository/MemberRepositoryQuerydslImpl.java
  src/main/java/wegrus/clubwebsite/service/ClubService.java
  src/main/java/wegrus/clubwebsite/service/GroupService.java
  src/main/java/wegrus/clubwebsite/service/MemberService.java
Labels: bug, enhancement

#89 게시물 등록/조회 api 파일 기능 추가
  src/main/java/wegrus/clubwebsite/controller/PostController.java
  src/main/java/wegrus/clubwebsite/dto/post/PostDto.java
  src/main/java/wegrus/clubwebsite/dto/post/PostUnknownDto.java
  src/main/java/wegrus/clubwebsite/entity/post/Post.java
  src/main/java/wegrus/clubwebsite/entity/post/PostFile.java
  src/main/java/wegrus/clubwebsite/repository/PostFileRepository.java
  src/main/java/wegrus/clubwebsite/service/PostService.java
  src/main/java/wegrus/clubwebsite/util/AmazonS3Util.java
  src/main/java/wegrus/clubwebsite/util/FileUtil.java
  src/main/java/wegrus/clubwebsite/vo/File.java
  src/main/resources/application.yml
Labels: enhancement

#91 게시물 조회 시 댓글 현재 유저가 추천했는지 유무 확인
  src/main/java/wegrus/clubwebsite/dto/post/ReplyDto.java
  src/main/java/wegrus/clubwebsite/service/PostService.java
Labels: enhancement

#93 HttpMediaTypeNotSupportedException 핸들러 추가
  src/main/java/wegrus/clubwebsite/advice/GlobalExceptionHandler.java
  src/main/java/wegrus/clubwebsite/dto/error/ErrorCode.java
Labels: enhancement

#97 CORS 설정 수정, 쿠키 도메인 설정 추가
  src/main/java/wegrus/clubwebsite/config/WebSecurityConfig.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
  src/main/java/wegrus/clubwebsite/dto/member/MemberInfoUpdateResponse.java
Labels: enhancement

#101 본인 정보 조회 API 추가
  src/main/java/wegrus/clubwebsite/config/WebSecurityConfig.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
Labels: enhancement

#103 로그아웃 API 추가
  src/main/java/wegrus/clubwebsite/config/WebSecurityConfig.java
  src/main/java/wegrus/clubwebsite/controller/MemberController.java
Labels: enhancement

#104 게시판 조회 응답 데이터 추가 등
  src/main/java/wegrus/clubwebsite/config/SetupConfig.java
  src/main/java/wegrus/clubwebsite/dto/post/BoardDto.java
  src/main/java/wegrus/clubwebsite/entity/post/Board.java
  src/main/java/wegrus/clubwebsite/entity/post/BoardCategories.java
Labels: enhancement

#105 이미지 파일 첨부시 다운로드 문제
  src/main/java/wegrus/clubwebsite/util/AmazonS3Util.java
Labels: bug
